# Generated by Django 2.1.7 on 2019-03-03 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField(max_length=4096)),
                ('mr', models.TextField(max_length=4096)),
                ('informativeness_avg', models.FloatField(default=0)),
                ('naturalness_avg', models.FloatField(default=0)),
                ('quality_avg', models.FloatField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.ScoringDataset')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringSentenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informativeness', models.IntegerField()),
                ('naturalness', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('ip', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sentenceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.ScoringSentence')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
