# Generated by Django 2.1.7 on 2019-06-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringdataset',
            name='informativeness_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoringdataset',
            name='naturalness_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoringdataset',
            name='quality_avg',
            field=models.FloatField(default=0),
        ),
    ]
