# Generated by Django 2.0.7 on 2018-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181102_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/site-media/photos/profiles/matthew.png', null=True, upload_to='static/site-media/photos/profiles/'),
        ),
    ]
