# Generated by Django 2.0.7 on 2018-10-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.IntegerField()),
                ('ip', models.CharField(max_length=120)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.Sentence')),
            ],
        ),
    ]
