# Generated by Django 2.1.7 on 2019-02-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('polarityAvg', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.IntegerField()),
                ('ip', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sentenceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.Sentence')),
            ],
        ),
    ]
