# Generated by Django 2.1.7 on 2019-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_sentencehistory_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentencehistory',
            old_name='polarity',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='polarityAvg',
        ),
        migrations.AddField(
            model_name='sentence',
            name='informativeness_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='naturalness_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='quality_avg',
            field=models.FloatField(default=0),
        ),
    ]
