# Generated by Django 2.0.7 on 2018-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_sentencehistory_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentencehistory',
            old_name='sentence',
            new_name='sentenceId',
        ),
        migrations.AddField(
            model_name='sentence',
            name='polarityAvg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentencehistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
