# Generated by Django 2.0.7 on 2018-11-04 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_auto_20181104_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencehistory',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
