# Generated by Django 2.1.7 on 2019-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0005_auto_20190227_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='is_MR',
            field=models.BooleanField(default=False),
        ),
    ]
