# Generated by Django 2.1.7 on 2019-03-03 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagger', '0006_sentence_is_mr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.IntegerField()),
                ('ip', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='is_MR',
        ),
        migrations.AddField(
            model_name='sentence',
            name='mr',
            field=models.TextField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='polarity_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentimenthistory',
            name='sentenceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.Sentence'),
        ),
        migrations.AddField(
            model_name='sentimenthistory',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
