# Generated by Django 2.1.7 on 2019-03-03 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagger', '0007_auto_20190303_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField(max_length=4096)),
                ('mr', models.TextField(max_length=4096)),
                ('informativeness_avg', models.FloatField(default=0)),
                ('naturalness_avg', models.FloatField(default=0)),
                ('quality_avg', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringSentenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informativeness', models.IntegerField()),
                ('naturalness', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('ip', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sentenceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.ScoringSentence')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentimenthistory',
            name='sentenceId',
        ),
        migrations.RemoveField(
            model_name='sentimenthistory',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='informativeness_avg',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='mr',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='naturalness_avg',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='number',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='polarity_avg',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='quality_avg',
        ),
        migrations.RemoveField(
            model_name='sentencehistory',
            name='informativeness',
        ),
        migrations.RemoveField(
            model_name='sentencehistory',
            name='naturalness',
        ),
        migrations.RemoveField(
            model_name='sentencehistory',
            name='quality',
        ),
        migrations.AddField(
            model_name='sentence',
            name='polarityAvg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentencehistory',
            name='polarity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SentimentHistory',
        ),
    ]
