# Generated by Django 2.1.7 on 2019-03-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0008_auto_20190303_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='scoringsentence',
            name='dataset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tagger.ScoringDataset'),
            preserve_default=False,
        ),
    ]
