# Generated by Django 2.1.7 on 2019-03-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0009_auto_20190303_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringsentence',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='scoringsentencehistory',
            name='sentenceId',
        ),
        migrations.RemoveField(
            model_name='scoringsentencehistory',
            name='userId',
        ),
        migrations.DeleteModel(
            name='ScoringDataset',
        ),
        migrations.DeleteModel(
            name='ScoringSentence',
        ),
        migrations.DeleteModel(
            name='ScoringSentenceHistory',
        ),
    ]
